version: '2'

services:
  
  orbeon-app:
    image: tiredofit/orbeon
    container_name: orbeon-app
    ports:
    - 8080:8080
    environment:
    - VIRTUAL_HOST=orbeon.hostname.com
    - VIRTUAL_NETWORK=orbeon-proxy
    - VIRTUAL_PORT=8080
    - LETSENCRYPT_HOST=orbeon.hostname.com
    - LETSENCRYPT_EMAIL=user@hostname.com

    - ZABBIX_HOSTNAME=orbeon-app

    - DB_TYPE=none
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

